// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikethsaeyybeyhoolrlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZXRoc2FleXliZXlob29scmxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzA1NDUsImV4cCI6MjA2NzYwNjU0NX0.bObO1tK5AltniqGGPqo_e0KfhPnm7_3F6r7vLNGk6i4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});